[workspace]
members = [
    "programs/umay"
]

[patch.crates-io]
anchor-lang = { git = "https://github.com/coral-xyz/anchor", tag = "v0.29.0" }
anchor-spl = { git = "https://github.com/coral-xyz/anchor", tag = "v0.29.0" }
